echo "This is test filefor checking connectivity between"
echo "********* GIT and Jenkins *********"
echo " latest changes in prog to test in jenkins"
echo " With NGROK"
echo " *** Time is $(date) ***"
